export const INITIALIZE_DONE = 'INITIALIZE_DONE';
export const SET_SALMOS_FILTER = 'SET_SALMOS_FILTER';
export const SET_SALMO_CONTENT = 'SET_SALMO_CONTENT';
export const SET_ABOUT_VISIBLE = 'SET_ABOUT_VISIBLE';
export const SET_SETTINGS_VALUE = 'SET_SETTINGS_VALUE';
export const SET_SALMOS_ADD_VISIBLE = 'SET_SALMOS_ADD_VISIBLE';
export const SALMO_SELECT = 'SALMO_SELECT';
export const SALMO_ADD_TO_LIST = 'SALMO_ADD_TO_LIST';
