export const es_audios = {
  1: require('./Que estupendo que alegria.mp3'),
  2: require('./Aleluya bendecid al Señor (1987).mp3'),
  3: require('./Aleluya han llegado las bodas.mp3'),
  4: require('./Aleluya pascual.mp3'),
  5: require('./Alzaos puertas.mp3'),
  6: require('./Amen amen amen.mp3'),
  7: require('./A ti Señor se debe la alabanza en Sion.mp3'),
  8: require('./A tu luz Señor vemos la luz.mp3'),
  9: require('./Abba padre.mp3'),
  10: require('./Abraham.mp3'),
  11: require('./Aclamad al Señor.mp3'),
  12: require('./Adonde te escondiste amado cantico espiritual.mp3'),
  13: require('./Adonde te escondiste amado convivencia 2015.mp3'),
  14: require('./Adonde te escondiste amado.mp3'),
  15: require('./Al despertar.mp3'),
  16: require('./Alabad al Señor en el cielo.mp3'),
  17: require('./Alegria ha nacido el salvador.mp3'),
  18: require('./Aleluya alabad al Señor.mp3'),
  19: require('./A la victima pascual.mp3'),
  20: require('./A nadie demos ocasion de tropiezo.mp3'),
  21: require('./A ti levanto mis ojos.mp3'),
  22: require('./A ti Señor en mi clamor imploro.mp3'),
  23: require('./A ti Señor levanto mi alma.mp3'),
  24: require('./Amo al Señor.mp3'),
  25: require('./Aquedah.mp3'),
  26: require('./Asi habla el amen.mp3'),
  27: require('./Ave maria i.mp3'),
  28: require('./Ave maria ii (1984).mp3'),
  29: require('./Babilonia criminal.mp3'),
  30: require('./Balaam.mp3'),
  31: require('./Bendecire al Señor en todo tiempo.mp3'),
  32: require('./Bendice alma mia a Yahveh.mp3'),
  33: require('./Bendicion del agua.mp3'),
  34: require('./Bendita eres tu maria.mp3'),
  35: require('./Bendito sea Dios.mp3'),
  36: require('./Benedictus.mp3'),
  37: require('./Cantad a Dios.mp3'),
  38: require('./Cantad al Señor.mp3'),
  39: require('./Cantico 3 jovenes - Bendito eres tu Señor.mp3'),
  40: require('./Cantico 3 jovenes - Criaturas todas del Señor.mp3'),
  41: require('./Canto de debora.mp3'),
  42: require('./Canto de los niños.mp3'),
  43: require('./Canto de Moises.mp3'),
  44: require('./Charitas christi.mp3'),
  45: require('./Como condenados a muerte.mp3'),
  46: require('./Como destila la miel.mp3'),
  47: require('./Como el impulso que siente la ira.mp3'),
  48: require('./Como es maravilloso.mp3'),
  49: require('./Como la cierva anhela.mp3'),
  50: require('./Como lirio entre los cardos.mp3'),
  51: require('./Como oveja que ve como se llevan su corderito al matadero.mp3'),
  52: require('./Consolad a mi pueblo.mp3'),
  53: require('./Cordero de Dios.mp3'),
  54: require('./Credo.mp3'),
  55: require('./Cristo es la luz.mp3'),
  56: require('./Cuando dormia.mp3'),
  57: require('./Cuando el Señor.mp3'),
  58: require('./Cuando Israel salio de Egipto.mp3'),
  59: require('./Cuarto canto del siervo de Yahveh no hay en el parecer.mp3'),
  60: require('./Dayenú.mp3'),
  61: require('./De profundis.mp3'),
  62: require('./Decid a los de corazon cansado.mp3'),
  63: require('./Delante de los angeles.mp3'),
  64: require('./Dia de reposo.mp3'),
  65: require('./Dice el Señor a mi Señor.mp3'),
  66: require('./Dichoso el hombre.mp3'),
  67: require('./Dios te salve (salve regina).mp3'),
  68: require('./El buen pastor ha subido.mp3'),
  69: require('./El combate escatologico.mp3'),
  70: require('./El espiritu del Señor esta sobre mi.mp3'),
  71: require('./El jacal de los pastores.mp3'),
  72: require('./El lagarero.mp3'),
  73: require('./El Mesias león para vencer.mp3'),
  74: require('./El mismo Dios.mp3'),
  75: require('./El necio piensa que Dios no existe.mp3'),
  76: require('./El pueblo que caminaba en las tinieblas.mp3'),
  77: require('./El sembrador.mp3'),
  78: require('./El Señor anuncia una noticia.mp3'),
  79: require('./El Señor es mi pastor.mp3'),
  80: require('./El Señor me ha dado tercer canto del siervo de Yahveh.mp3'),
  81: require('./Eli eli lama sacabtani.mp3'),
  82: require('./En medio de aquel gentio.mp3'),
  83: require('./En una noche oscura.mp3'),
  84: require('./Eres digno de tomar el libro.mp3'),
  85: require('./Eres hermoso.mp3'),
  86: require('./Es paciente.mp3'),
  87: require('./Escondeme en lo oculto de tu tienda.mp3'),
  88: require('./Estan rotas mis ataduras.mp3'),
  89: require('./Este es el mandamiento mio.mp3'),
  90: require('./Evenu shalom alejem.mp3'),
  91: require('./Extiendo mis manos.mp3'),
  92: require('./Exultad justos en el se±or.mp3'),
  93: require('./Felicidad para el hombre.mp3'),
  94: require('./Gloria.mp3'),
  95: require('./Gracias a Yahveh (penitencial).mp3'),
  96: require('./Gritad jubilosos.mp3'),
  97: require('./Hacia ti morada santa.mp3'),
  98: require('./Hasta cuando.mp3'),
  99: require('./He aqui mi siervo.mp3'),
  100: require('./He aqui que nuestro espejo es el Señor.mp3'),
  101: require('./He aqui que vengo presto.mp3'),
  102: require('./He esperado en el Señor.mp3'),
  103: require('./Hermosa eres amiga mia.mp3'),
  104: require('./Hijas de jerusalen.mp3'),
  105: require('./Himno a la caridad.mp3'),
  106: require('./Himno a la kenosis.mp3'),
  107: require('./Himno cristo luz anuncio pascua.mp3'),
  108: require('./Himno de adviento.mp3'),
  109: require('./Himno de pascua.mp3'),
  110: require('./Huye amado mío.mp3'),
  111: require('./Id y anunciad a mis hermanos.mp3'),
  112: require('./Improperios.mp3'),
  113: require('./Jacob.mp3'),
  114: require('./Jerusalen reconstruida.mp3'),
  115: require('./Jesus recorria las ciudades (1982).mp3'),
  116: require('./La cordera de Dios.mp3'),
  117: require('./La cruz gloriosa.mp3'),
  118: require('./La espada.mp3'),
  119: require('./La marcha es dura.mp3'),
  120: require('./La paloma voló.mp3'),
  121: require('./La siega de las naciones.mp3'),
  122: require('./La voz de mi amado.mp3'),
  123: require('./Las armas de la luz.mp3'),
  124: require('./Levanto mis ojos a los montes.mp3'),
  125: require('./Llegue hasta tu presencia mi clamor.mp3'),
  126: require('./Llevame al cielo.mp3'),
  127: require('./Magnificat.mp3'),
  128: require('./Maria casa de bendicion.mp3'),
  129: require('./Maria de jasna göra.mp3'),
  130: require('./Maria madre de la iglesia.mp3'),
  131: require('./Maria madre del camino ardiente.mp3'),
  132: require('./Maria pequeña maria.mp3'),
  133: require('./Me enseñaráss el camino de la vida.mp3'),
  134: require('./Me has seducido Señor.mp3'),
  135: require('./Me robaste el corazon.mp3'),
  136: require('./Mirad que estupendo.mp3'),
  137: require('./Misericordia mía misericordia.mp3'),
  138: require('./Mucho me han perseguido.mp3'),
  139: require('./Ninguno puede servir a dos señores.mp3'),
  140: require('./No esta aqui resucito.mp3'),
  141: require('./No he de morir.mp3'),
  142: require('./No resistais al mal.mp3'),
  143: require('./No sufras por los malvados.mp3'),
  144: require('./Noli me tangere.mp3'),
  145: require('./Oh Dios por tu nombre salvame.mp3'),
  146: require('./Oh Dios tu eres mi Dios.mp3'),
  147: require('./Oh jesus amor mio.mp3'),
  148: require('./Oh muerte donde esta tu victoria.mp3'),
  149: require('./Os tomare de entre las naciones.mp3'),
  150: require('./Padrenuestro.mp3'),
  151: require('./Paloma incorrupta.mp3'),
  152: require('./Pentecostes.mp3'),
  153: require('./Por el amor de mis amigos.mp3'),
  154: require('./Por qué las gentes conjuran.mp3'),
  155: require('./Porque mi yugo es suave.mp3'),
  156: require('./Pregon pascual.mp3'),
  157: require('./Que amables son tus moradas.mp3'),
  158: require('./A la cena del cordero.mp3'),
  159: require('./Quien es esta que sube del desierto.mp3'),
  160: require('./Quien nos separará.mp3'),
  161: require('./Quiero andar madre a jerusalen.mp3'),
  162: require('./Quiero cantar.mp3'),
  163: require('./Resucito cantores.mp3'),
  164: require('./Resurrexit.mp3'),
  165: require('./Salve reina de los cielos.mp3'),
  166: require('./Santo (1982).mp3'),
  167: require('./Santo (1989).mp3'),
  168: require('./Santo (palestina 74).mp3'),
  169: require('./Santo es santo.mp3'),
  170: require('./Santo palomeras.mp3'),
  171: require('./Santo roma 77.mp3'),
  172: require('./Se encontraron dos angeles.mp3'),
  173: require('./Secuencia de pentecostes.mp3'),
  174: require('./Secuencia del corpus christi.mp3'),
  175: require('./Segundo canto del siervo de Yahveh.mp3'),
  176: require('./Señor ayudame a no dudar de ti.mp3'),
  177: require('./Señor mi corazon ya no es ambicioso.mp3'),
  178: require('./Señor no me corrijas en tu colera.mp3'),
  179: require('./Señor tu me escrutas.mp3'),
  180: require('./Sermon del monte.mp3'),
  181: require('./Shema Israel.mp3'),
  182: require('./Shlom leg mariam.mp3'),
  183: require('./Si el Señor no contruye la casa.mp3'),
  184: require('./Si habeis resucitado con cristo.mp3'),
  185: require('./Si hoy escuchais su voz (1981).mp3'),
  186: require('./Si me he refugiado cantores.mp3'),
  187: require('./Sientate solitario y silencioso.mp3'),
  188: require('./Sion madre de los pueblos.mp3'),
  189: require('./Sola a solo.mp3'),
  190: require('./Stabat mater.mp3'),
  191: require('./Suba el esposo al leno de su talamo.mp3'),
  192: require('./Sube Dios entre aclamaciones.mp3'),
  193: require('./Te estoy llamando Señor.mp3'),
  194: require('./Te he manifestado mi pecado.mp3'),
  195: require('./Tedeum.mp3'),
  196: require('./Tu eres mi esperanza Señor.mp3'),
  197: require('./Tu has cubierto de verguenza la muerte.mp3'),
  198: require('./Tu que eres fiel.mp3'),
  199: require('./Un retono brota del tronco de jese.mp3'),
  200: require('./Una gran señal.mp3'),
  201: require('./Uri uri uria ura.mp3'),
  202: require('./Vamos ya pastores.mp3'),
  203: require('./Ven del libano.mp3'),
  204: require('./Ven hijo del hombre.mp3'),
  205: require('./Veni creator.mp3'),
  206: require('./Viene el Señor.mp3'),
  207: require('./Virgen de la maravilla.mp3'),
  208: require('./Vivid alegres.mp3'),
  209: require('./Vosotros sois la luz del mundo.mp3'),
  210: require('./Ya viene mi Dios.mp3'),
  211: require('./Zaqueo.mp3'),
  212: require('./Yo te amo Señor.mp3'),
  213: require('./Yo vengo a reunir.mp3'),
  214: require('./Yahveh tu eres mi Dios.mp3'),
};
