export const es_audios = {
  1: require('../assets/audios/es/Asi habla el amen.mp3'),
  2: require('../assets/audios/es/Como el impulso que siente la ira.mp3'),
  3: require('../assets/audios/es/Consolad a mi pueblo.mp3'),
  4: require('../assets/audios/es/Cuando dormia.mp3'),
  5: require('../assets/audios/es/Canto de debora.mp3'),
  6: require('../assets/audios/es/Dichoso el hombre.mp3'),
  7: require('../assets/audios/es/El Señor me ha dado tercer canto del siervo de Yahveh.mp3'),
  8: require('../assets/audios/es/El combate escatologico.mp3'),
  9: require('../assets/audios/es/El lagarero.mp3'),
  10: require('../assets/audios/es/El sembrador.mp3'),
  11: require('../assets/audios/es/He aqui que nuestro espejo es el Señor.mp3'),
  12: require('../assets/audios/es/Jacob.mp3'),
  13: require('../assets/audios/es/Ninguno puede servir a dos señores.mp3'),
  14: require('../assets/audios/es/Señor mi corazon ya no es ambicioso.mp3'),
  15: require('../assets/audios/es/Señor tu me escrutas.mp3'),
  16: require('../assets/audios/es/Shema Israel.mp3'),
  17: require('../assets/audios/es/Sientate solitario y silencioso.mp3'),
  18: require('../assets/audios/es/Tu has cubierto de verguenza la muerte.mp3'),
  19: require('../assets/audios/es/A la victima pascual.mp3'),
  20: require('../assets/audios/es/A nadie demos ocasion de tropiezo.mp3'),
  21: require('../assets/audios/es/A ti levanto mis ojos.mp3'),
  22: require('../assets/audios/es/A ti Señor en mi clamor imploro.mp3'),
  23: require('../assets/audios/es/A ti Señor levanto mi alma.mp3'),
  24: require('../assets/audios/es/A ti Señor se debe la alabanza en Sion.mp3'),
  25: require('../assets/audios/es/Abraham.mp3'),
  26: require('../assets/audios/es/Aclamad al Señor.mp3'),
  27: require('../assets/audios/es/Al despertar.mp3'),
  28: require('../assets/audios/es/Alabad al Señor en el cielo.mp3'),
  29: require('../assets/audios/es/Aleluya alabad al Señor.mp3'),
  30: require('../assets/audios/es/Aleluya bendecid al Señor (1987).mp3'),
  31: require('../assets/audios/es/Aleluya han llegado las bodas.mp3'),
  32: require('../assets/audios/es/Alzaos puertas.mp3'),
  33: require('../assets/audios/es/Amo al Señor.mp3'),
  34: require('../assets/audios/es/Aquedah.mp3'),
  35: require('../assets/audios/es/Ave maria i.mp3'),
  36: require('../assets/audios/es/Ave maria ii (1984).mp3'),
  37: require('../assets/audios/es/Babilonia criminal.mp3'),
  38: require('../assets/audios/es/Balaam.mp3'),
  39: require('../assets/audios/es/Bendecire al Señor en todo tiempo.mp3'),
  40: require('../assets/audios/es/Bendice alma mia a Yahveh.mp3'),
  41: require('../assets/audios/es/Bendita eres tu maria.mp3'),
  42: require('../assets/audios/es/Cantico 3 jovenes - Bendito eres tu Señor.mp3'),
  43: require('../assets/audios/es/Benedictus.mp3'),
  44: require('../assets/audios/es/Cantad al Señor.mp3'),
  45: require('../assets/audios/es/Canto de Moises.mp3'),
  46: require('../assets/audios/es/Charitas christi.mp3'),
  47: require('../assets/audios/es/Cantico 3 jovenes - Criaturas todas del Señor.mp3'),
  48: require('../assets/audios/es/Como la cierva anhela.mp3'),
  49: require('../assets/audios/es/Como es maravilloso.mp3'),
  50: require('../assets/audios/es/Cristo es la luz.mp3'),
  51: require('../assets/audios/es/Cuando Israel salio de Egipto.mp3'),
  52: require('../assets/audios/es/Cuando el Señor.mp3'),
  53: require('../assets/audios/es/Dayenú.mp3'),
  54: require('../assets/audios/es/De profundis.mp3'),
  55: require('../assets/audios/es/Decid a los de corazon cansado.mp3'),
  56: require('../assets/audios/es/Delante de los angeles.mp3'),
  57: require('../assets/audios/es/Dice el Señor a mi Señor.mp3'),
  58: require('../assets/audios/es/Dia de reposo.mp3'),
  59: require('../assets/audios/es/El Señor anuncia una noticia.mp3'),
  60: require('../assets/audios/es/El Señor es mi pastor.mp3'),
  61: require('../assets/audios/es/El jacal de los pastores.mp3'),
  62: require('../assets/audios/es/El necio piensa que Dios no existe.mp3'),
  63: require('../assets/audios/es/El pueblo que caminaba en las tinieblas.mp3'),
  64: require('../assets/audios/es/Eli eli lama sacabtani.mp3'),
  65: require('../assets/audios/es/Eres digno de tomar el libro.mp3'),
  66: require('../assets/audios/es/Eres hermoso.mp3'),
  67: require('../assets/audios/es/Escondeme en lo oculto de tu tienda.mp3'),
  68: require('../assets/audios/es/Estan rotas mis ataduras.mp3'),
  69: require('../assets/audios/es/Evenu shalom alejem.mp3'),
  70: require('../assets/audios/es/Exultad justos en el se±or.mp3'),
  72: require('../assets/audios/es/Felicidad para el hombre.mp3'),
  73: require('../assets/audios/es/Gracias a Yahveh (penitencial).mp3'),
  74: require('../assets/audios/es/Gritad jubilosos.mp3'),
  75: require('../assets/audios/es/Hacia ti morada santa.mp3'),
  76: require('../assets/audios/es/Hasta cuando.mp3'),
  77: require('../assets/audios/es/He aqui mi siervo.mp3'),
  78: require('../assets/audios/es/He aqui que vengo presto.mp3'),
  79: require('../assets/audios/es/He esperado en el Señor.mp3'),
  80: require('../assets/audios/es/Hijas de jerusalen.mp3'),
  81: require('../assets/audios/es/Himno cristo luz anuncio pascua.mp3'),
  82: require('../assets/audios/es/Himno a la kenosis.mp3'),
  83: require('../assets/audios/es/Himno de adviento.mp3'),
  84: require('../assets/audios/es/Himno de pascua.mp3'),
  86: require('../assets/audios/es/Huye amado mío.mp3'),
  87: require('../assets/audios/es/Id y anunciad a mis hermanos.mp3'),
  88: require('../assets/audios/es/Improperios.mp3'),
  89: require('../assets/audios/es/Jerusalen reconstruida.mp3'),
  90: require('../assets/audios/es/La marcha es dura.mp3'),
  92: require('../assets/audios/es/La siega de las naciones.mp3'),
  93: require('../assets/audios/es/Levanto mis ojos a los montes.mp3'),
  94: require('../assets/audios/es/Llegue hasta tu presencia mi clamor.mp3'),
  95: require('../assets/audios/es/Llevame al cielo.mp3'),
  96: require('../assets/audios/es/Magnificat.mp3'),
  97: require('../assets/audios/es/Maria de jasna göra.mp3'),
  98: require('../assets/audios/es/Maria casa de bendicion.mp3'),
  99: require('../assets/audios/es/Maria madre de la iglesia.mp3'),
  100: require('../assets/audios/es/Maria madre del camino ardiente.mp3'),
  101: require('../assets/audios/es/Maria pequeña maria.mp3'),
  102: require('../assets/audios/es/Me enseñaráss el camino de la vida.mp3'),
  103: require('../assets/audios/es/Me has seducido Señor.mp3'),
  104: require('../assets/audios/es/Mirad que estupendo.mp3'),
  105: require('../assets/audios/es/Misericordia mía misericordia.mp3'),
  106: require('../assets/audios/es/Mucho me han perseguido.mp3'),
  107: require('../assets/audios/es/No esta aqui resucito.mp3'),
  108: require('../assets/audios/es/Cuarto canto del siervo de Yahveh no hay en el parecer.mp3'),
  109: require('../assets/audios/es/Oh Dios por tu nombre salvame.mp3'),
  110: require('../assets/audios/es/Oh jesus amor mio.mp3'),
  113: require('../assets/audios/es/Oh muerte donde esta tu victoria.mp3'),
  114: require('../assets/audios/es/Os tomare de entre las naciones.mp3'),
  115: require('../assets/audios/es/Pentecostes.mp3'),
  116: require('../assets/audios/es/Por el amor de mis amigos.mp3'),
  117: require('../assets/audios/es/Canto de los niños.mp3'),
  118: require('../assets/audios/es/Por qué las gentes conjuran.mp3'),
  119: require('../assets/audios/es/Porque mi yugo es suave.mp3'),
  120: require('../assets/audios/es/Que amables son tus moradas.mp3'),
  121: require('../assets/audios/es/Que estupendo que alegria.mp3'),
  122: require('../assets/audios/es/Quiero andar madre a jerusalen.mp3'),
  123: require('../assets/audios/es/Quiero cantar.mp3'),
  124: require('../assets/audios/es/Quien es esta que sube del desierto.mp3'),
  125: require('../assets/audios/es/Quien nos separará.mp3'),
  126: require('../assets/audios/es/Resucito cantores.mp3'),
  127: require('../assets/audios/es/Salve reina de los cielos.mp3'),
  128: require('../assets/audios/es/Se encontraron dos angeles.mp3'),
  129: require('../assets/audios/es/Señor ayudame a no dudar de ti.mp3'),
  131: require('../assets/audios/es/Señor no me corrijas en tu colera.mp3'),
  132: require('../assets/audios/es/Shlom leg mariam.mp3'),
  133: require('../assets/audios/es/Si el Señor no contruye la casa.mp3'),
  134: require('../assets/audios/es/Si hoy escuchais su voz (1981).mp3'),
  135: require('../assets/audios/es/Si me he refugiado cantores.mp3'),
  136: require('../assets/audios/es/Sion madre de los pueblos.mp3'),
  137: require('../assets/audios/es/Sola a solo.mp3'),
  138: require('../assets/audios/es/Stabat mater.mp3'),
  139: require('../assets/audios/es/Te estoy llamando Señor.mp3'),
  140: require('../assets/audios/es/Te he manifestado mi pecado.mp3'),
  141: require('../assets/audios/es/Tu eres mi esperanza Señor.mp3'),
  142: require('../assets/audios/es/Un retono brota del tronco de jese.mp3'),
  143: require('../assets/audios/es/Una gran señal.mp3'),
  144: require('../assets/audios/es/Uri uri uria ura.mp3'),
  145: require('../assets/audios/es/Vamos ya pastores.mp3'),
  146: require('../assets/audios/es/Secuencia de pentecostes.mp3'),
  147: require('../assets/audios/es/Ven del libano.mp3'),
  148: require('../assets/audios/es/Ven hijo del hombre.mp3'),
  149: require('../assets/audios/es/Veni creator.mp3'),
  150: require('../assets/audios/es/Viene el Señor.mp3'),
  151: require('../assets/audios/es/Virgen de la maravilla.mp3'),
  152: require('../assets/audios/es/Vivid alegres.mp3'),
  153: require('../assets/audios/es/Vosotros sois la luz del mundo.mp3'),
  154: require('../assets/audios/es/Ya viene mi Dios.mp3'),
  155: require('../assets/audios/es/Yahveh tu eres mi Dios.mp3'),
  156: require('../assets/audios/es/Yo te amo Señor.mp3'),
  157: require('../assets/audios/es/Yo vengo a reunir.mp3'),
  158: require('../assets/audios/es/A la cena del cordero.mp3'),
  159: require('../assets/audios/es/Abba padre.mp3'),
  160: require('../assets/audios/es/Bendito sea Dios.mp3'),
  161: require('../assets/audios/es/Como condenados a muerte.mp3'),
  162: require('../assets/audios/es/Como destila la miel.mp3'),
  163: require('../assets/audios/es/Como lirio entre los cardos.mp3'),
  164: require('../assets/audios/es/El espiritu del Señor esta sobre mi.mp3'),
  165: require('../assets/audios/es/El mismo Dios.mp3'),
  166: require('../assets/audios/es/En una noche oscura.mp3'),
  167: require('../assets/audios/es/Segundo canto del siervo de Yahveh.mp3'),
  168: require('../assets/audios/es/Extiendo mis manos.mp3'),
  169: require('../assets/audios/es/Hermosa eres amiga mia.mp3'),
  170: require('../assets/audios/es/Himno a la caridad.mp3'),
  171: require('../assets/audios/es/La cruz gloriosa.mp3'),
  172: require('../assets/audios/es/Jesus recorria las ciudades (1982).mp3'),
  173: require('../assets/audios/es/La cordera de Dios.mp3'),
  174: require('../assets/audios/es/La paloma voló.mp3'),
  175: require('../assets/audios/es/La voz de mi amado.mp3'),
  176: require('../assets/audios/es/Las armas de la luz.mp3'),
  177: require('../assets/audios/es/No resistais al mal.mp3'),
  178: require('../assets/audios/es/No sufras por los malvados.mp3'),
  179: require('../assets/audios/es/Noli me tangere.mp3'),
  180: require('../assets/audios/es/Sermon del monte.mp3'),
  181: require('../assets/audios/es/Aleluya pascual.mp3'),
  182: null,
  183: require('../assets/audios/es/Amen amen amen.mp3'),
  184: null,
  185: null,
  186: require('../assets/audios/es/Bendicion del agua.mp3'),
  187: null,
  188: require('../assets/audios/es/Credo.mp3'),
  189: require('../assets/audios/es/Gloria.mp3'),
  190: null,
  191: require('../assets/audios/es/Cordero de Dios.mp3'),
  192: null,
  193: null,
  194: require('../assets/audios/es/Padrenuestro.mp3'),
  195: null,
  196: null,
  197: null,
  198: null,
  199: null,
  200: null,
  201: null,
  202: require('../assets/audios/es/Pregon pascual.mp3'),
  203: require('../assets/audios/es/Santo (1982).mp3'),
  204: require('../assets/audios/es/Santo (1989).mp3'),
  205: require('../assets/audios/es/Santo es santo.mp3'),
  206: require('../assets/audios/es/Santo (palestina 74).mp3'),
  207: require('../assets/audios/es/Santo palomeras.mp3'),
  208: require('../assets/audios/es/Santo roma 77.mp3'),
  209: require('../assets/audios/es/Secuencia del corpus christi.mp3'),
  210: require('../assets/audios/es/Tedeum.mp3'),
  211: require('../assets/audios/es/Zaqueo.mp3'),
  212: require('../assets/audios/es/El Mesias león para vencer.mp3'),
  213: require('../assets/audios/es/En medio de aquel gentio.mp3'),
  214: require('../assets/audios/es/Me robaste el corazon.mp3'),
  215: require('../assets/audios/es/Paloma incorrupta.mp3'),
  216: require('../assets/audios/es/Si habeis resucitado con cristo.mp3'),
  217: require('../assets/audios/es/Resurrexit.mp3'),
  218: require('../assets/audios/es/Este es el mandamiento mio.mp3'),
  219: require('../assets/audios/es/Oh Dios tu eres mi Dios.mp3'),
  220: require('../assets/audios/es/Como oveja que ve como se llevan su corderito al matadero.mp3'),
  221: require('../assets/audios/es/Adonde te escondiste amado.mp3'),
  222: require('../assets/audios/es/Alegria ha nacido el salvador.mp3'),
  223: null,
  224: require('../assets/audios/es/Sube Dios entre aclamaciones.mp3'),
  225: require('../assets/audios/es/Suba el esposo al leno de su talamo.mp3'),
  226: null,
  227: null,
  228: null,
  229: null,
  230: null,
  231: null,
  232: null,
  233: null,
  234: null,
  235: null,
  236: null,
  237: null,
  238: null,
  239: require('../assets/audios/es/Cantad a Dios.mp3'),
  240: null,
  241: null,
  242: null,
  243: null,
  244: null,
  245: null,
  246: null,
  247: null,
  248: null,
  249: null,
  250: null,
  251: null,
  252: null,
  253: null,
  254: null,
  255: null,
  256: null,
  257: null,
  258: null,
  259: null,
  260: null,
  261: require('../assets/audios/es/Es paciente.mp3'),
  262: null,
  263: require('../assets/audios/es/La espada.mp3'),
  264: null,
  265: null,
  266: null,
  267: require('../assets/audios/es/A tu luz Señor vemos la luz.mp3'),
  268: null,
  269: null,
  270: null,
  271: null,
  272: null,
};
