require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'iResucito' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"],
   # to enable hermes on iOS, change `false` to `true` and then install pods
   :hermes_enabled => true)

  target 'iResucitoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'iResucito-tvOS' do
  # Pods for iResucito-tvOS

  target 'iResucito-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end