export const es_audios = {
  1: require('./es/Asi habla el amen.mp3'),
  2: require('./es/Como el impulso que siente la ira.mp3'),
  3: require('./es/Consolad a mi pueblo.mp3'),
  4: require('./es/Cuando dormia.mp3'),
  5: require('./es/Canto de debora.mp3'),
  6: require('./es/Dichoso el hombre.mp3'),
  7: require('./es/El Señor me ha dado tercer canto del siervo de Yahveh.mp3'),
  8: require('./es/El combate escatologico.mp3'),
  9: require('./es/El lagarero.mp3'),
  10: require('./es/El sembrador.mp3'),
  11: require('./es/He aqui que nuestro espejo es el Señor.mp3'),
  12: require('./es/Jacob.mp3'),
  13: require('./es/Ninguno puede servir a dos señores.mp3'),
  14: require('./es/Señor mi corazon ya no es ambicioso.mp3'),
  15: require('./es/Señor tu me escrutas.mp3'),
  16: require('./es/Shema Israel.mp3'),
  17: require('./es/Sientate solitario y silencioso.mp3'),
  18: require('./es/Tu has cubierto de verguenza la muerte.mp3'),
  19: require('./es/A la victima pascual.mp3'),
  20: require('./es/A nadie demos ocasion de tropiezo.mp3'),
  21: require('./es/A ti levanto mis ojos.mp3'),
  22: require('./es/A ti Señor en mi clamor imploro.mp3'),
  23: require('./es/A ti Señor levanto mi alma.mp3'),
  24: require('./es/A ti Señor se debe la alabanza en Sion.mp3'),
  25: require('./es/Abraham.mp3'),
  26: require('./es/Aclamad al Señor.mp3'),
  27: require('./es/Al despertar.mp3'),
  28: require('./es/Alabad al Señor en el cielo.mp3'),
  29: require('./es/Aleluya alabad al Señor.mp3'),
  30: require('./es/Aleluya bendecid al Señor (1987).mp3'),
  31: require('./es/Aleluya han llegado las bodas.mp3'),
  32: require('./es/Alzaos puertas.mp3'),
  33: require('./es/Amo al Señor.mp3'),
  34: require('./es/Aquedah.mp3'),
  35: require('./es/Ave maria i.mp3'),
  36: require('./es/Ave maria ii (1984).mp3'),
  37: require('./es/Babilonia criminal.mp3'),
  38: require('./es/Balaam.mp3'),
  39: require('./es/Bendecire al Señor en todo tiempo.mp3'),
  40: require('./es/Bendice alma mia a Yahveh.mp3'),
  41: require('./es/Bendita eres tu maria.mp3'),
  42: require('./es/Cantico 3 jovenes - Bendito eres tu Señor.mp3'),
  43: require('./es/Benedictus.mp3'),
  44: require('./es/Cantad al Señor.mp3'),
  45: require('./es/Canto de Moises.mp3'),
  46: require('./es/Charitas christi.mp3'),
  47: require('./es/Cantico 3 jovenes - Criaturas todas del Señor.mp3'),
  48: require('./es/Como la cierva anhela.mp3'),
  49: require('./es/Como es maravilloso.mp3'),
  50: require('./es/Cristo es la luz.mp3'),
  51: require('./es/Cuando Israel salio de Egipto.mp3'),
  52: require('./es/Cuando el Señor.mp3'),
  53: require('./es/Dayenú.mp3'),
  54: require('./es/De profundis.mp3'),
  55: require('./es/Decid a los de corazon cansado.mp3'),
  56: require('./es/Delante de los angeles.mp3'),
  57: require('./es/Dice el Señor a mi Señor.mp3'),
  58: require('./es/Dia de reposo.mp3'),
  59: require('./es/El Señor anuncia una noticia.mp3'),
  60: require('./es/El Señor es mi pastor.mp3'),
  61: require('./es/El jacal de los pastores.mp3'),
  62: require('./es/El necio piensa que Dios no existe.mp3'),
  63: require('./es/El pueblo que caminaba en las tinieblas.mp3'),
  64: require('./es/Eli eli lama sacabtani.mp3'),
  65: require('./es/Eres digno de tomar el libro.mp3'),
  66: require('./es/Eres hermoso.mp3'),
  67: require('./es/Escondeme en lo oculto de tu tienda.mp3'),
  68: require('./es/Estan rotas mis ataduras.mp3'),
  69: require('./es/Evenu shalom alejem.mp3'),
  70: require('./es/Exultad justos en el se±or.mp3'),
  72: require('./es/Felicidad para el hombre.mp3'),
  73: require('./es/Gracias a Yahveh (penitencial).mp3'),
  74: require('./es/Gritad jubilosos.mp3'),
  75: require('./es/Hacia ti morada santa.mp3'),
  76: require('./es/Hasta cuando.mp3'),
  77: require('./es/He aqui mi siervo.mp3'),
  78: require('./es/He aqui que vengo presto.mp3'),
  79: require('./es/He esperado en el Señor.mp3'),
  80: require('./es/Hijas de jerusalen.mp3'),
  81: require('./es/Himno cristo luz anuncio pascua.mp3'),
  82: require('./es/Himno a la kenosis.mp3'),
  83: require('./es/Himno de adviento.mp3'),
  84: require('./es/Himno de pascua.mp3'),
  86: require('./es/Huye amado mío.mp3'),
  87: require('./es/Id y anunciad a mis hermanos.mp3'),
  88: require('./es/Improperios.mp3'),
  89: require('./es/Jerusalen reconstruida.mp3'),
  90: require('./es/La marcha es dura.mp3'),
  92: require('./es/La siega de las naciones.mp3'),
  93: require('./es/Levanto mis ojos a los montes.mp3'),
  94: require('./es/Llegue hasta tu presencia mi clamor.mp3'),
  95: require('./es/Llevame al cielo.mp3'),
  96: require('./es/Magnificat.mp3'),
  97: require('./es/Maria de jasna göra.mp3'),
  98: require('./es/Maria casa de bendicion.mp3'),
  99: require('./es/Maria madre de la iglesia.mp3'),
  100: require('./es/Maria madre del camino ardiente.mp3'),
  101: require('./es/Maria pequeña maria.mp3'),
  102: require('./es/Me enseñaráss el camino de la vida.mp3'),
  103: require('./es/Me has seducido Señor.mp3'),
  104: require('./es/Mirad que estupendo.mp3'),
  105: require('./es/Misericordia mía misericordia.mp3'),
  106: require('./es/Mucho me han perseguido.mp3'),
  107: require('./es/No esta aqui resucito.mp3'),
  108: require('./es/Cuarto canto del siervo de Yahveh no hay en el parecer.mp3'),
  109: require('./es/Oh Dios por tu nombre salvame.mp3'),
  110: require('./es/Oh jesus amor mio.mp3'),
  113: require('./es/Oh muerte donde esta tu victoria.mp3'),
  114: require('./es/Os tomare de entre las naciones.mp3'),
  115: require('./es/Pentecostes.mp3'),
  116: require('./es/Por el amor de mis amigos.mp3'),
  117: require('./es/Canto de los niños.mp3'),
  118: require('./es/Por qué las gentes conjuran.mp3'),
  119: require('./es/Porque mi yugo es suave.mp3'),
  120: require('./es/Que amables son tus moradas.mp3'),
  121: require('./es/Que estupendo que alegria.mp3'),
  122: require('./es/Quiero andar madre a jerusalen.mp3'),
  123: require('./es/Quiero cantar.mp3'),
  124: require('./es/Quien es esta que sube del desierto.mp3'),
  125: require('./es/Quien nos separará.mp3'),
  126: require('./es/Resucito cantores.mp3'),
  127: require('./es/Salve reina de los cielos.mp3'),
  128: require('./es/Se encontraron dos angeles.mp3'),
  129: require('./es/Señor ayudame a no dudar de ti.mp3'),
  131: require('./es/Señor no me corrijas en tu colera.mp3'),
  132: require('./es/Shlom leg mariam.mp3'),
  133: require('./es/Si el Señor no contruye la casa.mp3'),
  134: require('./es/Si hoy escuchais su voz (1981).mp3'),
  135: require('./es/Si me he refugiado cantores.mp3'),
  136: require('./es/Sion madre de los pueblos.mp3'),
  137: require('./es/Sola a solo.mp3'),
  138: require('./es/Stabat mater.mp3'),
  139: require('./es/Te estoy llamando Señor.mp3'),
  140: require('./es/Te he manifestado mi pecado.mp3'),
  141: require('./es/Tu eres mi esperanza Señor.mp3'),
  142: require('./es/Un retono brota del tronco de jese.mp3'),
  143: require('./es/Una gran señal.mp3'),
  144: require('./es/Uri uri uria ura.mp3'),
  145: require('./es/Vamos ya pastores.mp3'),
  146: require('./es/Secuencia de pentecostes.mp3'),
  147: require('./es/Ven del libano.mp3'),
  148: require('./es/Ven hijo del hombre.mp3'),
  149: require('./es/Veni creator.mp3'),
  150: require('./es/Viene el Señor.mp3'),
  151: require('./es/Virgen de la maravilla.mp3'),
  152: require('./es/Vivid alegres.mp3'),
  153: require('./es/Vosotros sois la luz del mundo.mp3'),
  154: require('./es/Ya viene mi Dios.mp3'),
  155: require('./es/Yahveh tu eres mi Dios.mp3'),
  156: require('./es/Yo te amo Señor.mp3'),
  157: require('./es/Yo vengo a reunir.mp3'),
  158: require('./es/A la cena del cordero.mp3'),
  159: require('./es/Abba padre.mp3'),
  160: require('./es/Bendito sea Dios.mp3'),
  161: require('./es/Como condenados a muerte.mp3'),
  162: require('./es/Como destila la miel.mp3'),
  163: require('./es/Como lirio entre los cardos.mp3'),
  164: require('./es/El espiritu del Señor esta sobre mi.mp3'),
  165: require('./es/El mismo Dios.mp3'),
  166: require('./es/En una noche oscura.mp3'),
  167: require('./es/Segundo canto del siervo de Yahveh.mp3'),
  168: require('./es/Extiendo mis manos.mp3'),
  169: require('./es/Hermosa eres amiga mia.mp3'),
  170: require('./es/Himno a la caridad.mp3'),
  171: require('./es/La cruz gloriosa.mp3'),
  172: require('./es/Jesus recorria las ciudades (1982).mp3'),
  173: require('./es/La cordera de Dios.mp3'),
  174: require('./es/La paloma voló.mp3'),
  175: require('./es/La voz de mi amado.mp3'),
  176: require('./es/Las armas de la luz.mp3'),
  177: require('./es/No resistais al mal.mp3'),
  178: require('./es/No sufras por los malvados.mp3'),
  179: require('./es/Noli me tangere.mp3'),
  180: require('./es/Sermon del monte.mp3'),
  181: require('./es/Aleluya pascual.mp3'),
  182: null,
  183: require('./es/Amen amen amen.mp3'),
  184: null,
  185: null,
  186: require('./es/Bendicion del agua.mp3'),
  187: null,
  188: require('./es/Credo.mp3'),
  189: require('./es/Gloria.mp3'),
  190: null,
  191: require('./es/Cordero de Dios.mp3'),
  192: null,
  193: null,
  194: require('./es/Padrenuestro.mp3'),
  195: null,
  196: null,
  197: null,
  198: null,
  199: null,
  200: null,
  201: null,
  202: require('./es/Pregon pascual.mp3'),
  203: require('./es/Santo (1982).mp3'),
  204: require('./es/Santo (1989).mp3'),
  205: require('./es/Santo es santo.mp3'),
  206: require('./es/Santo (palestina 74).mp3'),
  207: require('./es/Santo palomeras.mp3'),
  208: require('./es/Santo roma 77.mp3'),
  209: require('./es/Secuencia del corpus christi.mp3'),
  210: require('./es/Tedeum.mp3'),
  211: require('./es/Zaqueo.mp3'),
  212: require('./es/El Mesias león para vencer.mp3'),
  213: require('./es/En medio de aquel gentio.mp3'),
  214: require('./es/Me robaste el corazon.mp3'),
  215: require('./es/Paloma incorrupta.mp3'),
  216: require('./es/Si habeis resucitado con cristo.mp3'),
  217: require('./es/Resurrexit.mp3'),
  218: require('./es/Este es el mandamiento mio.mp3'),
  219: require('./es/Oh Dios tu eres mi Dios.mp3'),
  220: require('./es/Como oveja que ve como se llevan su corderito al matadero.mp3'),
  221: require('./es/Adonde te escondiste amado.mp3'),
  222: require('./es/Alegria ha nacido el salvador.mp3'),
  223: null,
  224: require('./es/Sube Dios entre aclamaciones.mp3'),
  225: require('./es/Suba el esposo al leno de su talamo.mp3'),
  226: null,
  227: null,
  228: null,
  229: null,
  230: null,
  231: null,
  232: null,
  233: null,
  234: null,
  235: null,
  236: null,
  237: null,
  238: null,
  239: require('./es/Cantad a Dios.mp3'),
  240: null,
  241: null,
  242: null,
  243: null,
  244: null,
  245: null,
  246: null,
  247: null,
  248: null,
  249: null,
  250: null,
  251: null,
  252: null,
  253: null,
  254: null,
  255: null,
  256: null,
  257: null,
  258: null,
  259: null,
  260: null,
  261: require('./es/Es paciente.mp3'),
  262: null,
  263: require('./es/La espada.mp3'),
  264: null,
  265: null,
  266: null,
  267: require('./es/A tu luz Señor vemos la luz.mp3'),
  268: null,
  269: null,
  270: null,
  271: null,
  272: null,
};
