# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.61"
default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
    # carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Enviar version beta a TestFlight (ej 3.0.1-0) Apple TestFlight"
  lane :beta do |options|
    match(type: "appstore") # more information: https://codesigning.guide
    if options[:newVersion]
      increment_version_number
      increment_build_number(build_number: "0")
    elsif !options[:skipBuild]
      increment_build_number
    end
    gym(scheme: "iResucito", configuration: options[:config]) # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Enviar version nueva al AppStore (ej 3.0.1-0)"
  lane :release do |options|
    match(type: "appstore")
    # snapshot
    increment_version_number
    increment_build_number(build_number: "0")
    gym(scheme: "iResucito") # Build your app - more options available
    deliver(force: true, run_precheck_before_submit: false)
    # frameit
  end

  desc "Enviar version existente (nuevo build) al AppStore (ej 3.0.1-0 => 3.0.1-1)"
  lane :release_update do |options|
    match(type: "appstore")
    # snapshot
    increment_build_number
    gym(scheme: "iResucito") # Build your app - more options available
    deliver(force: true, run_precheck_before_submit: false)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
