mv "A Te Signore Si Deve Lode In Sion.txt" "A te signore si deve lode in sion.txt"
mv "Abbá Padre.txt" "Abbá padre.txt"
mv "Abramo.txt" "Abramo.txt"
mv "Acclamate Al Signore.txt" "Acclamate al signore.txt"
mv "Acclamazioni Al Vangelo.txt" "Acclamazioni al vangelo.txt"
mv "Agnella Di Dio.txt" "Agnella di dio.txt"
mv "Akedá.txt" "Akedá.txt"
mv "Al Risveglio Mi Sazier„ Del Tuo Volto, Signor.txt" "Al risveglio mi sazier„ del tuo volto, signor.txt"
mv "Alla Vittima Pasquale.txt" "Alla vittima pasquale.txt"
mv "Alleluja Pasquale.txt" "Alleluja pasquale.txt"
mv "Alzate O Porte.txt" "Alzate o porte.txt"
mv "Alzo Gli Occhi Verso I Monti.txt" "Alzo gli occhi verso i monti.txt"
mv "Amen - Amen - Amen.txt" "Amen - amen - amen.txt"
mv "Amo Il Signore.txt" "Amo il signore.txt"
mv "Andate Ed Annunziate Ai Miei Fratelli.txt" "Andate ed annunziate ai miei fratelli.txt"
mv "Andiamo, Giá Pastori.txt" "Andiamo, giá pastori.txt"
mv "Ave Maria (1984).txt" "Ave maria (1984).txt"
mv "Ave Maria.txt" "Ave maria.txt"
mv "Benedetta Sei Tu, Maria.txt" "Benedetta sei tu, maria.txt"
mv "Benedetto Sia Iddio.txt" "Benedetto sia iddio.txt"
mv "Benedetto sei tu Signore.txt" "Benedetto sei tu signore.txt"
mv "Benedici Anima Mia Il Signore.txt" "Benedici anima mia il signore.txt"
mv "Benedici Anima Mia Jahvé.txt" "Benedici anima mia jahvé.txt"
mv "Benediró Il Signore In Ogni Tempo.txt" "Benediró il signore in ogni tempo.txt"
mv "Benedite Il Signore.txt" "Benedite il signore.txt"
mv "Benedizione Dell.txt" "Benedizione dell.txt"
mv "Benedizione Per La Celebrazione Penitenziale.txt" "Benedizione per la celebrazione penitenziale.txt"
mv "C'erano Due Angeli.txt" "C'erano due angeli.txt"
mv "C'é Un Tempo Per Ogni Cosa.txt" "C'é un tempo per ogni cosa.txt"
mv "Cantiamo, Cantiamo.txt" "Cantiamo, cantiamo.txt"
mv "Cantico Di Mosé.txt" "Cantico di mosé.txt"
mv "Cantico Di Zaccaria.txt" "Cantico di zaccaria.txt"
mv "Canto Dei Bambini Nella Veglia Di Pasqua.txt" "Canto dei bambini nella veglia di pasqua.txt"
mv "Canto Dei Liberati.txt" "Canto dei liberati.txt"
mv "Canto Dei Tre Giovani Nella Fornace.txt" "Canto dei tre giovani nella fornace.txt"
mv "Canto Dell'agnello.txt" "Canto dell'agnello.txt"
mv "Canto Dell.txt" "Canto dell.txt"
mv "Canto Di Balaam.txt" "Canto di balaam.txt"
mv "Canto Di Giosué.txt" "Canto di giosué.txt"
mv "Caritas Christi.txt" "Caritas christi.txt"
mv "Carmen '63.txt" "Carmen '63.txt"
mv "Che Mi Baci.txt" "Che mi baci.txt"
mv "Chi Ci Separerá.txt" "Chi ci separerá.txt"
mv "Chi é Colei.txt" "Chi é colei.txt"
mv "Come Condannati A Morte.txt" "Come condannati a morte.txt"
mv "Come Lo Slancio Dell'ira.txt" "Come lo slancio dell'ira.txt"
mv "Come Stilla Il Miele.txt" "Come stilla il miele.txt"
mv "Come Una Cerva Anela.txt" "Come una cerva anela.txt"
mv "Come é Bello, Come Dá Gioia.txt" "Come é bello, come dá gioia.txt"
mv "Consolate Il Mio Popolo.txt" "Consolate il mio popolo.txt"
mv "Cosﬁ Parla L'amen.txt" "Cosﬁ parla l'amen.txt"
mv "Cristo Gesú é Il Signore.txt" "Cristo gesú é il signore.txt"
mv "Dajenî.txt" "Dajenî.txt"
mv "Dal Profondo A Te Grido.txt" "Dal profondo a te grido.txt"
mv "Davanti Agli Angeli.txt" "Davanti agli angeli.txt"
mv "Debora.txt" "Debora.txt"
mv "Dice Il Signore Al Mio Signore.txt" "Dice il signore al mio signore.txt"
mv "Dite Agli Smarriti Di Cuore.txt" "Dite agli smarriti di cuore.txt"
mv "Dá Lode Al Signore.txt" "Dá lode al signore.txt"
mv "Ecco Lo Specchio Nostro.txt" "Ecco lo specchio nostro.txt"
mv "Ecco Qui Io Vengo Presto.txt" "Ecco qui io vengo presto.txt"
mv "Eli, Eli, Lammá Sabactani.txt" "Eli, eli, lammá sabactani.txt"
mv "Esultate Giusti Nel Signore.txt" "Esultate giusti nel signore.txt"
mv "Evenu Shalom Alejem.txt" "Evenu shalom alejem.txt"
mv "Felice L'uomo.txt" "Felice l'uomo.txt"
mv "Felicitá Per L'uomo.txt" "Felicitá per l'uomo.txt"
mv "Figlie Di Gerusalemme.txt" "Figlie di gerusalemme.txt"
mv "Fino A Quando.txt" "Fino a quando.txt"
mv "Gesî Percorreva Tutte Le Cittá.txt" "Gesî percorreva tutte le cittá.txt"
mv "Giacobbe.txt" "Giacobbe.txt"
mv "Giorno Di Riposo.txt" "Giorno di riposo.txt"
mv "Giunga La Mia Preghiera Fino A Te.txt" "Giunga la mia preghiera fino a te.txt"
mv "Giá Viene Il Mio Dio.txt" "Giá viene il mio dio.txt"
mv "Giá Viene Il Regno.txt" "Giá viene il regno.txt"
mv "Gloria A Dio Nell.txt" "Gloria a dio nell.txt"
mv "Gloria, Gloria, Gloria.txt" "Gloria, gloria, gloria.txt"
mv "Grazie A Jahvé.txt" "Grazie a jahvé.txt"
mv "Gridate Con Gioia.txt" "Gridate con gioia.txt"
mv "Guardate Com'É Bello, Gustate Quant'É Soave.txt" "Guardate com'É bello, gustate quant'É soave.txt"
mv "Gustate E Vedete.txt" "Gustate e vedete.txt"
mv "Ho Sperato, Ho Sperato Nel Signore.txt" "Ho sperato, ho sperato nel signore.txt"
mv "Ho Steso Le Mie Mani.txt" "Ho steso le mie mani.txt"
mv "Il Pigiatore.txt" "Il pigiatore.txt"
mv "Il Popolo Che Camminava Nelle Tenebre.txt" "Il popolo che camminava nelle tenebre.txt"
mv "Il Seminatore.txt" "Il seminatore.txt"
mv "Il Sermone Della Montagna.txt" "Il sermone della montagna.txt"
mv "Il Signore Annuncia Una Notizia.txt" "Il signore annuncia una notizia.txt"
mv "Il Signore Mi Ha Dato - Iii Canto Del Servo.txt" "Il signore mi ha dato - iii canto del servo.txt"
mv "Il Signore é Il Mio Pastore.txt" "Il signore é il mio pastore.txt"
mv "Il Signore é Mia Luce E Mia Salvezza.txt" "Il signore é mia luce e mia salvezza.txt"
mv "In Una Notte Oscura.txt" "In una notte oscura.txt"
mv "Innalzer„ La Coppa Di Salvezza.txt" "Innalzer„ la coppa di salvezza.txt"
mv "Inno Alla Caritá.txt" "Inno alla caritá.txt"
mv "Inno Alla Croce Gloriosa.txt" "Inno alla croce gloriosa.txt"
mv "Inno Di Avvento.txt" "Inno di avvento.txt"
mv "Inno Di Pasqua.txt" "Inno di pasqua.txt"
mv "Jahvé Tu Sei Il Mio Dio.txt" "Jahvé tu sei il mio dio.txt"
mv "La Colomba Voló.txt" "La colomba voló.txt"
mv "La Marcia é Dura.txt" "La marcia é dura.txt"
mv "La Mia Diletta é Per Me.txt" "La mia diletta é per me.txt"
mv "La Mietitura Delle Nazioni.txt" "La mietitura delle nazioni.txt"
mv "La Voce Del Mio Amato.txt" "La voce del mio amato.txt"
mv "Le Sue Fondamenta.txt" "Le sue fondamenta.txt"
mv "Lo Spirito Del Signore é Sopra Di Me.txt" "Lo spirito del signore é sopra di me.txt"
mv "Lo Stesso Iddio.txt" "Lo stesso iddio.txt"
mv "Lodate Iddio.txt" "Lodate iddio.txt"
mv "Lodate Il Signore Dai Cieli.txt" "Lodate il signore dai cieli.txt"
mv "Lodate Il Signore.txt" "Lodate il signore.txt"
mv "Magnificat.txt" "Magnificat.txt"
mv "Maria Di Jasna Góra.txt" "Maria di jasna góra.txt"
mv "Maria Madre Della Chiesa.txt" "Maria madre della chiesa.txt"
mv "Maria, Casa Di Benedizione.txt" "Maria, casa di benedizione.txt"
mv "Maria, Madre Del Cammino Ardente.txt" "Maria, madre del cammino ardente.txt"
mv "Maria, Piccola Maria.txt" "Maria, piccola maria.txt"
mv "Mi Hai Sedotto, Signore.txt" "Mi hai sedotto, signore.txt"
mv "Mi Hai Sedotto.txt" "Mi hai sedotto.txt"
mv "Mi Indicherai Il Sentiero Della Vita.txt" "Mi indicherai il sentiero della vita.txt"
mv "Misericordia Dio, Misericordia.txt" "Misericordia dio, misericordia.txt"
mv "Molto Mi Hanno Perseguitato.txt" "Molto mi hanno perseguitato.txt"
mv "Nessuno Pu„ Servire Due Padroni.txt" "Nessuno pu„ servire due padroni.txt"
mv "Noli Me Tangere.txt" "Noli me tangere.txt"
mv "Non C'É In Lui Bellezza.txt" "Non c'É in lui bellezza.txt"
mv "Non Moriró.txt" "Non moriró.txt"
mv "Non Resistete Al Male.txt" "Non resistete al male.txt"
mv "Non Ti Adirare.txt" "Non ti adirare.txt"
mv "O Cieli Piovete Dall'alto.txt" "O cieli piovete dall'alto.txt"
mv "O Dio Tu Sei Il Mio Dio.txt" "O dio tu sei il mio dio.txt"
mv "O Gesî Amore Mio.txt" "O gesî amore mio.txt"
mv "O Morte Dov'é La Tua Vittoria.txt" "O morte dov'é la tua vittoria.txt"
mv "O Signore Nostro Dio.txt" "O signore nostro dio.txt"
mv "Oh Dio Per Il Tuo Nome Salvami.txt" "Oh dio per il tuo nome salvami.txt"
mv "Omelia Pasquale Di Melitone Di Sardi.txt" "Omelia pasquale di melitone di sardi.txt"
mv "Pentecoste.txt" "Pentecoste.txt"
mv "Per Amore Dei Miei Fratelli.txt" "Per amore dei miei fratelli.txt"
mv "Perchê Le Genti Congiurano.txt" "Perchê le genti congiurano.txt"
mv "Pietá Di Me O Dio.txt" "Pietá di me o dio.txt"
mv "Portami In Cielo.txt" "Portami in cielo.txt"
mv "Quando Dormivo.txt" "Quando dormivo.txt"
mv "Quando Il Signore.txt" "Quando il signore.txt"
mv "Quando Israele Era Un Bimbo.txt" "Quando israele era un bimbo.txt"
mv "Quando Israele Uscﬁ Dall'egitto.txt" "Quando israele uscﬁ dall'egitto.txt"
mv "Quanto Sono Amabili Le Tue Dimore.txt" "Quanto sono amabili le tue dimore.txt"
mv "Risuscitó.txt" "Risuscitó.txt"
mv "Rivestitevi Dell'armatura Di Dio.txt" "Rivestitevi dell'armatura di dio.txt"
mv "Sale Dio Tra Acclamazioni.txt" "Sale dio tra acclamazioni.txt"
mv "Salve, Regina Dei Cieli.txt" "Salve, regina dei cieli.txt"
mv "Santo Del Tempo Ordinario.txt" "Santo del tempo ordinario.txt"
mv "Santo Santo Santo.txt" "Santo santo santo.txt"
mv "Santo.txt" "Santo.txt"
mv "Se Encontraron Dos Μngeles.txt" "Se encontraron dos Μngeles.txt"
mv "Se Il Signore Non Costruisce La Casa.txt" "Se il signore non costruisce la casa.txt"
mv "Se Nel Signore Mi Sono Rifugiato.txt" "Se nel signore mi sono rifugiato.txt"
mv "Se Oggi Ascoltate La Sua Voce.txt" "Se oggi ascoltate la sua voce.txt"
mv "Shemá Israel.txt" "Shemá israel.txt"
mv "Shlom Lech Mariám.txt" "Shlom lech mariám.txt"
mv "Siedi Solitario E Silenzioso.txt" "Siedi solitario e silenzioso.txt"
mv "Signore Aiutami, Signore.txt" "Signore aiutami, signore.txt"
mv "Signore Ascolta La Mia Preghiera.txt" "Signore ascolta la mia preghiera.txt"
mv "Signore Tu Mi Scruti E Mi Conosci.txt" "Signore tu mi scruti e mi conosci.txt"
mv "Signore, Il Mio Cuore Non Ha Piî Pretese.txt" "Signore, il mio cuore non ha piî pretese.txt"
mv "Signore, Non Punirmi Nel Tuo Sdegno.txt" "Signore, non punirmi nel tuo sdegno.txt"
mv "Sorga Dio.txt" "Sorga dio.txt"
mv "Sui Fiumi Di Babilonia.txt" "Sui fiumi di babilonia.txt"
mv "Te Deum.txt" "Te deum.txt"
mv "Ti Amo Signore.txt" "Ti amo signore.txt"
mv "Ti Ho Manifestato Il Mio Peccato.txt" "Ti ho manifestato il mio peccato.txt"
mv "Ti Sto Chiamando.txt" "Ti sto chiamando.txt"
mv "Ti Vedranno I Re - Ii Canto Del Servo.txt" "Ti vedranno i re - ii canto del servo.txt"
mv "Tu Che Abiti Nei Giardini.txt" "Tu che abiti nei giardini.txt"
mv "Tu Sei Il Piî Bello.txt" "Tu sei il piî bello.txt"
mv "Tu Sei La Mia Speranza Signore.txt" "Tu sei la mia speranza signore.txt"
mv "Un Germoglio Spunta Dal Tronco Di Jesse.txt" "Un germoglio spunta dal tronco di jesse.txt"
mv "Una Donna Vestita Di Sole.txt" "Una donna vestita di sole.txt"
mv "Urí, Urí, Urá.txt" "Urí, urí, urá.txt"
mv "Vedo I Cieli Aperti.txt" "Vedo i cieli aperti.txt"
mv "Venite A Me Voi Tutti.txt" "Venite a me voi tutti.txt"
mv "Venite Applaudiamo Al Signore.txt" "Venite applaudiamo al signore.txt"
mv "Vergine Della Meraviglia.txt" "Vergine della meraviglia.txt"
mv "Verso Te, O Cittá Santa.txt" "Verso te, o cittá santa.txt"
mv "Viene Il Signore Vestito Di Maestá.txt" "Viene il signore vestito di maestá.txt"
mv "Vieni Dal Libano.txt" "Vieni dal libano.txt"
mv "Vieni, Figlio Dell'uomo.txt" "Vieni, figlio dell'uomo.txt"
mv "Voglio Andare A Gerusalemme.txt" "Voglio andare a gerusalemme.txt"
mv "Voglio Cantare.txt" "Voglio cantare.txt"
mv "rename.sh" "Rename.sh"
mv "É La Pasqua Del Signore.txt" "É la pasqua del signore.txt"
